### ISSUE TITLE
Restore original copyright and license

### ISSUE THREAD

**Issue by aallan** [ForsakenNGS/PicoLED#1]
Hi there, I'm the head of documentation at Raspberry Pi. We've noticed that you have reused code, e.g. [ws2812.pio](https://github.com/ForsakenNGS/PicoLED/blob/master/WS2812B.pio), but have removed the copyright statement, comments, and license from these files. 

<img width="1832" alt="ws2812 pio" src="https://user-images.githubusercontent.com/53625/113833284-653cf080-9781-11eb-9da8-04c27518e29e.png">

Please restore the copyright header, and original license. You have republished the code under the GPL v3, which is not something you have the legal right to do as you are not the original copyright holder, and the code was originally licensed under a BSD 3 clause license.

**Comment by ForsakenNGS** [comment]
First of all, it neither was nor is my intention to violate any licenses.

There is no copyright because I didn't straight up copy the file. I followed the documentation (because that usually is the correct way to use hardware efficently) and made only minor changes anlong the way. ( https://datasheets.raspberrypi.org/pico/raspberry-pi-pico-c-sdk.pdf pages 36-44 )
That one is actually published under Creative Commons?
```
The documentation of the RP2040 microcontroller is licensed under a Creative Commons Attribution-NoDerivatives 4.0
International (CC BY-ND).
```
I have no issue with putting the copyright notice there, I simply wasn't aware because of the way I did write that file. But, if I understood you correctly, by including the "copyrighted file" in my project, I would also have to change the license of my project? It's not like I have an issue using a different open-source license, as long as my code can be used by the communinty without limitations, but it would certainly leave a sour taste.

To be competely frank, it feels wrong being "chased down" for following the documentation. It's not like I am trying to steal anything or profit off of someone elses work. In the opposite, I want to support the platorm, which obviously is the reason I published it open-source instead of keeping it to myself.

**Comment by aallan** [comment]
> First of all, it neither was nor is my intention to violate any licenses.
> 
> There is no copyright because I didn't straight up copy the file. I followed the documentation… The documentation of the RP2040 microcontroller is licensed under a Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND).

The source-code excerpts in the documentation are pulled from [pico-sdk](https://github.com/raspberrypi/pico-sdk) and [pico-examples](https://github.com/raspberrypi/pico-examples) which are both under the BSD license. All excerpts have a link above them directly back to the source file in the repository from where they've been included.

> I have no issue with putting the copyright notice there…

Thanks, that's all we're asking.

> But, if I understood you correctly, by including the "copyrighted file" in my project, I would also have to change the license of my project? It's not like I have an issue using a different open-source license, as long as my code can be used by the community without limitations, but it would certainly leave a sour taste.

No, I don't believe you have to relicense the project. The BSD 3 clause license only requires that,

_Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:_

_1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission._

Unlike the original 4-clause BSD license, the 3-clause BSD license is compatible with the GPL. If you restore the copyright and license to the files you have copied from the [pico-sdk](https://github.com/raspberrypi/pico-sdk) or [pico-examples](https://github.com/raspberrypi/pico-examples) repositories then the rest of your project can be distributed under the GPL without problems if that is what you prefer.

**Comment by ForsakenNGS** [comment]
Allright, thanks for the clarification. I will change it this week.

**Comment by aallan** [comment]
Many thanks!
